import type { FullQuestion } from "./types";

// Original discrete practice items. Timing targets are estimates, not calibrated norms.
type Row = [string, string[], number, string, string, string, number, string];
const groups: { topic: string; section: string; rows: Row[] }[] = [
  {
    topic: "Acids & bases",
    section: "C/P",
    rows: [
      [
        "A buffer contains equal concentrations of a weak acid and its conjugate base. The acid has pKa = 6.8. What is the buffer pH?",
        ["3.4", "6.8", "7.0", "13.6"],
        1,
        "The Henderson–Hasselbalch equation gives pH = pKa + log([base]/[acid]). Equal concentrations give log(1) = 0, so pH = 6.8. A buffer need not have neutral pH.",
        "Compare the base-to-acid ratio.",
        "Use pH = pKa + log([base]/[acid]); log(1) is zero.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A weak acid has pKa = 5.0. At pH 6.0, what is the ratio of conjugate base to undissociated acid?",
        ["1:10", "1:1", "10:1", "100:1"],
        2,
        "pH − pKa = log([base]/[acid]) = 1. The ratio is therefore 10:1. Higher pH favors the deprotonated form.",
        "Subtract pKa from pH.",
        "Convert a base-10 logarithm of 1 into a concentration ratio.",
        75,
        "Quantitative reasoning",
      ],
      [
        "At 25 °C, a dilute aqueous solution has [H+] = 1 × 10⁻³ M. What is [OH−]? Use Kw = 1 × 10⁻¹⁴.",
        ["1 × 10⁻¹¹ M", "1 × 10⁻⁷ M", "1 × 10⁻³ M", "1 × 10¹¹ M"],
        0,
        "Kw = [H+][OH−]. Dividing 10⁻¹⁴ by 10⁻³ gives [OH−] = 10⁻¹¹ M. The acidic solution has less hydroxide than neutral water.",
        "Use the product of the two ion concentrations.",
        "When dividing powers of ten, subtract the exponents.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A small amount of strong acid is added to an acetate buffer containing appreciable acetic acid and acetate. Which reaction primarily limits the pH change?",
        [
          "Acetic acid consumes added H+",
          "Water converts all acetate into hydroxide",
          "Acetate releases H+",
          "Acetate accepts H+ to form acetic acid",
        ],
        3,
        "The conjugate base acetate accepts added protons, forming acetic acid. This consumes much of the added H+ while the buffer remains within its capacity.",
        "Identify the proton acceptor in the buffer.",
        "The negatively charged conjugate base can become the neutral weak acid.",
        60,
        "Concept application",
      ],
      [
        "At the equivalence point of a weak monoprotic acid titrated with a strong base at 25 °C, the solution is generally:",
        [
          "Acidic because some titrant remains",
          "Basic because the conjugate base reacts with water",
          "Neutral for every acid",
          "Basic because the weak acid releases OH− directly",
        ],
        1,
        "At equivalence the acid has been converted to its conjugate base. That base hydrolyzes water to produce OH−, so pH exceeds 7. Excess strong base is not required.",
        "Consider the species remaining after neutralization.",
        "Write A− + H₂O ⇌ HA + OH−.",
        60,
        "Concept application",
      ],
      [
        "A monoprotic weak acid is half-neutralized during titration with a strong base. Which statement holds under the usual dilute-solution approximation?",
        [
          "pH = pKa",
          "pH = 7 for every acid",
          "[H+] equals the initial acid concentration",
          "The conjugate base concentration is zero",
        ],
        0,
        "Half-neutralization leaves equal amounts of HA and A− in the same solution. Their concentration ratio is one, so the Henderson–Hasselbalch equation reduces to pH = pKa.",
        "Track how much HA has been converted into A−.",
        "At halfway to equivalence, the two buffer components have equal concentrations.",
        60,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Thermodynamics & equilibrium",
    section: "C/P",
    rows: [
      [
        "For a reaction, ΔH = −40 kJ/mol and ΔS = −100 J/(mol·K). What is ΔG at 300 K?",
        ["−70 kJ/mol", "+10 kJ/mol", "−10 kJ/mol", "+70 kJ/mol"],
        2,
        "Convert entropy to −0.100 kJ/(mol·K). ΔG = ΔH − TΔS = −40 − 300(−0.100) = −10 kJ/mol. Matching units is essential.",
        "Use ΔG = ΔH − TΔS.",
        "Convert joules to kilojoules before multiplying entropy by temperature.",
        90,
        "Quantitative reasoning",
      ],
      [
        "An enzyme catalyzes a reversible reaction at constant temperature. Which quantity does the enzyme change?",
        [
          "The equilibrium constant",
          "The activation free-energy barrier",
          "The standard reaction free energy",
          "The equilibrium product-to-reactant ratio",
        ],
        1,
        "An enzyme lowers the activation barrier and accelerates approach to equilibrium. It changes neither the free-energy difference between reactants and products nor the equilibrium constant.",
        "Separate reaction speed from equilibrium position.",
        "A catalyst provides a lower-barrier pathway for both directions.",
        60,
        "Concept application",
      ],
      [
        "For a reaction as written, the reaction quotient Q is less than the equilibrium constant K. Which direction is thermodynamically favored?",
        [
          "Reverse until all product disappears",
          "Neither direction because Q is always K",
          "Forward only if a catalyst is present",
          "Forward toward equilibrium",
        ],
        3,
        "ΔG = RT ln(Q/K). If Q < K, the logarithm is negative, so the forward reaction is favored. This predicts direction, not how quickly the reaction proceeds.",
        "Compare Q/K with one.",
        "The natural logarithm of a positive number below one is negative.",
        60,
        "Concept application",
      ],
      [
        "Heat is a product of an exothermic reversible reaction. At constant pressure, increasing temperature shifts equilibrium toward:",
        [
          "Reactants",
          "Products",
          "The side with more catalyst",
          "Products only if volumes are equal",
        ],
        0,
        "Increasing temperature favors the endothermic direction, which consumes heat. For a forward exothermic reaction, that direction is toward reactants.",
        "Treat heat as a product for this qualitative prediction.",
        "The system responds to added heat by favoring the direction that consumes it.",
        60,
        "Concept application",
      ],
      [
        "Under the same cellular conditions, reaction A has ΔG = +12 kJ/mol and reaction B has ΔG = −30 kJ/mol. If mechanistically coupled one-to-one, what is the net ΔG?",
        ["+42 kJ/mol", "+18 kJ/mol", "−18 kJ/mol", "−42 kJ/mol"],
        2,
        "Free-energy changes add for coupled reactions: +12 + (−30) = −18 kJ/mol. Merely placing unrelated reactions together would not establish mechanistic coupling.",
        "Free-energy changes are additive.",
        "Add the signed values for one occurrence of each reaction.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A system reaches dynamic chemical equilibrium in a closed container. Which statement is correct?",
        [
          "Reactant and product concentrations must be equal",
          "Forward and reverse reaction rates are equal",
          "Molecular reactions stop",
          "The equilibrium constant becomes zero",
        ],
        1,
        "At dynamic equilibrium the opposing rates match, so macroscopic concentrations remain constant. Their values need not be equal, and molecules continue reacting.",
        "Dynamic equilibrium is about matching rates.",
        "Constant concentration does not mean equal concentration or no molecular activity.",
        45,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Fluids & gases",
    section: "C/P",
    rows: [
      [
        "Water flows steadily through a rigid pipe. If its cross-sectional area falls to half its original value, how does speed change? Assume incompressible flow with no branches.",
        [
          "It halves",
          "It stays constant",
          "It falls to one fourth",
          "It doubles",
        ],
        3,
        "Continuity requires A₁v₁ = A₂v₂. Halving area doubles speed so the same fluid volume passes each section per unit time.",
        "Conserve volume flow rate.",
        "The product of area and speed remains constant.",
        60,
        "Quantitative reasoning",
      ],
      [
        "What is the gauge pressure 2.0 m below the surface of a stationary freshwater pool? Use density 1000 kg/m³ and g = 10 m/s².",
        ["2.0 × 10⁴ Pa", "2.0 × 10³ Pa", "1.0 × 10⁵ Pa", "2.0 × 10⁵ Pa"],
        0,
        "Gauge pressure is ρgh = 1000 × 10 × 2.0 = 20,000 Pa. Atmospheric pressure would be added only to calculate absolute pressure.",
        "Gauge pressure excludes atmospheric pressure.",
        "Multiply density, gravitational acceleration, and depth.",
        75,
        "Quantitative reasoning",
      ],
      [
        "For ideal laminar flow through a tube, the radius is doubled while pressure difference, length, and viscosity stay constant. By what factor does volume flow rate change?",
        ["2", "4", "16", "1/16"],
        2,
        "Poiseuille's law gives flow proportional to r⁴. Doubling radius multiplies flow by 2⁴ = 16, under the specified laminar-flow assumptions.",
        "Recall the radius dependence in Poiseuille's law.",
        "Raise the radius multiplication factor to the fourth power.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A sealed ideal gas is heated from 300 K to 450 K at constant volume. If its initial pressure is 100 kPa, what is its final pressure?",
        ["67 kPa", "150 kPa", "200 kPa", "450 kPa"],
        1,
        "At fixed amount and volume, P/T is constant. P₂ = 100 × 450/300 = 150 kPa. Temperature ratios must use kelvin.",
        "Use the ideal gas law with amount and volume fixed.",
        "Multiply initial pressure by the ratio of absolute temperatures.",
        75,
        "Quantitative reasoning",
      ],
      [
        "An ideal gas mixture contains 20% oxygen by mole fraction at a total pressure of 150 kPa. What is the oxygen partial pressure?",
        ["30 kPa", "75 kPa", "130 kPa", "750 kPa"],
        0,
        "Dalton's law gives partial pressure = mole fraction × total pressure = 0.20 × 150 = 30 kPa.",
        "A component contributes its mole fraction of the total pressure.",
        "Convert 20% to 0.20 before multiplying.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A fully submerged rigid object is moved deeper in an incompressible liquid of uniform density. Its volume stays constant. What happens to its buoyant force?",
        [
          "It increases with absolute pressure",
          "It decreases with depth",
          "It becomes zero",
          "It remains constant",
        ],
        3,
        "Buoyant force equals the weight of displaced liquid, ρVg. Density and displaced volume remain unchanged, so greater depth does not change the force.",
        "Use Archimedes' principle.",
        "Check whether displaced volume or liquid density changes.",
        60,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Amino acids & proteins",
    section: "B/B",
    rows: [
      [
        "At pH 7.4, which amino acid side chain is most likely to carry a negative charge?",
        ["Lysine", "Leucine", "Aspartate", "Serine"],
        2,
        "Aspartate's side-chain carboxyl group has a pKa well below 7.4 and is predominantly deprotonated. Lysine is typically positive; leucine and serine side chains are neutral.",
        "Look for an acidic side-chain functional group.",
        "A carboxyl group loses its proton when pH is well above its pKa.",
        60,
        "Concept application",
      ],
      [
        "A protein is placed in a buffer whose pH is below its isoelectric point. What is its approximate net charge?",
        [
          "Positive",
          "Negative",
          "Exactly zero at every pH",
          "Determined only by its mass",
        ],
        0,
        "Below its isoelectric point, a protein is more protonated and generally has a net positive charge. At the isoelectric point its average net charge is zero.",
        "Lower pH favors protonation.",
        "Compare the buffer pH with the pH where the protein's net charge is zero.",
        60,
        "Concept application",
      ],
      [
        "Which interaction most directly stabilizes an alpha helix's repeating secondary structure?",
        [
          "Disulfide bonds between every adjacent residue",
          "Peptide bonds between side chains",
          "Hydrogen bonds exclusively between side chains",
          "Hydrogen bonds between backbone carbonyl and amide groups",
        ],
        3,
        "An alpha helix is stabilized by hydrogen bonds between backbone C=O and N–H groups, commonly residues i and i+4. Side chains influence helix propensity but do not form the defining repeating hydrogen bonds.",
        "Focus on the repeating polypeptide backbone.",
        "Identify hydrogen-bond donors and acceptors in peptide groups.",
        60,
        "Concept application",
      ],
      [
        "A reducing reagent breaks disulfide bonds in a protein. Which residues formed those bonds?",
        [
          "Two methionines",
          "Two cysteines",
          "A lysine and an aspartate",
          "Two glycines",
        ],
        1,
        "Oxidation of two cysteine thiol groups creates a disulfide bond. Reduction restores the thiols. Methionine contains sulfur but lacks a thiol group.",
        "Which side chain contains a thiol?",
        "A disulfide links two sulfur atoms formerly present as –SH groups.",
        45,
        "Concept application",
      ],
      [
        "Which substitution is most likely to disrupt the hydrophobic core of a soluble globular protein?",
        [
          "Leucine to aspartate",
          "Leucine to isoleucine",
          "Valine to leucine",
          "Isoleucine to valine",
        ],
        0,
        "Replacing a nonpolar leucine with typically charged aspartate introduces an unfavorable polar group into a hydrophobic core. The other substitutions retain nonpolar side chains, although exact structural effects depend on context.",
        "Compare side-chain polarity and charge.",
        "A charged side chain is usually poorly accommodated in a nonpolar interior.",
        60,
        "Concept application",
      ],
      [
        "Under reducing SDS-PAGE conditions, migration of most denatured proteins primarily distinguishes which property?",
        [
          "Native enzymatic activity",
          "Original net charge at neutral pH",
          "Polypeptide molecular mass",
          "Native number of bound ligands",
        ],
        2,
        "SDS unfolds proteins and imparts a roughly uniform negative charge-to-mass ratio; reduction separates disulfide-linked chains. The gel therefore primarily separates polypeptides by mass, with smaller chains migrating farther.",
        "Consider what SDS and the reducing reagent do.",
        "Native shape and charge differences are largely removed before gel separation.",
        75,
        "Experimental reasoning",
      ],
    ],
  },
  {
    topic: "Genetics & gene expression",
    section: "B/B",
    rows: [
      [
        "Two heterozygous carriers of a fully penetrant autosomal recessive condition have a child. What is the probability that the child is affected?",
        ["0", "1/2", "3/4", "1/4"],
        3,
        "An Aa × Aa cross gives AA, Aa, Aa, and aa with equal probabilities. Only aa is affected, giving probability 1/4 for each child.",
        "Draw an Aa × Aa Punnett square.",
        "The affected genotype requires a recessive allele from each parent.",
        60,
        "Quantitative reasoning",
      ],
      [
        "A DNA template segment is 3′-TAC GGA-5′. Which RNA sequence is synthesized from it?",
        ["3′-AUG CCU-5′", "5′-AUG CCU-3′", "5′-TAC GGA-3′", "5′-UAC GGA-3′"],
        1,
        "RNA synthesis proceeds 5′ to 3′, complementary and antiparallel to the template. T pairs with A, A with U, C with G, and G with C, giving 5′-AUG CCU-3′.",
        "RNA is complementary and antiparallel to its template.",
        "Use uracil in RNA and write the product 5′ to 3′.",
        75,
        "Concept application",
      ],
      [
        "A single nucleotide is inserted near the start of a protein-coding sequence, within an exon and outside a splice site. What is the most likely immediate coding consequence?",
        [
          "A downstream reading-frame shift",
          "No change because codons have one base",
          "Deletion of the entire chromosome",
          "Only the previous amino acid changes",
        ],
        0,
        "Insertion of one nucleotide changes how downstream bases are grouped into triplet codons. This frameshift can alter many amino acids and create a premature stop; its precise extent depends on sequence.",
        "Codons are read in groups of three.",
        "An insertion not divisible by three changes the downstream grouping.",
        60,
        "Concept application",
      ],
      [
        "A heterozygote displays a phenotype intermediate between the two homozygotes. Which inheritance pattern best describes this observation?",
        [
          "Complete dominance",
          "Sex linkage",
          "Incomplete dominance",
          "Independent assortment",
        ],
        2,
        "Incomplete dominance produces an intermediate heterozygote phenotype. Codominance instead involves distinguishable expression of both allelic phenotypes, rather than an intermediate phenotype.",
        "Compare the heterozygote with both homozygotes.",
        "The dominant phenotype is not fully expressed in the heterozygote.",
        45,
        "Concept application",
      ],
      [
        "Which PCR component most directly determines the boundaries of the DNA segment amplified?",
        [
          "Free nucleotides",
          "Magnesium ions",
          "The reaction tube",
          "The pair of primers",
        ],
        3,
        "Primers anneal to sequences flanking the target on opposite strands and supply 3′ ends for extension. Their binding sites determine the amplified region.",
        "DNA polymerase must start from a preexisting 3′ end.",
        "The two short complementary oligonucleotides flank the target.",
        60,
        "Experimental reasoning",
      ],
      [
        "A eukaryotic pre-mRNA produces two mature mRNAs that retain different combinations of exons. What process explains this?",
        [
          "DNA replication",
          "Alternative splicing",
          "Chromosome nondisjunction",
          "Reverse transcription",
        ],
        1,
        "Alternative splicing joins different exon combinations from the same pre-mRNA. It can generate distinct protein isoforms without changing the underlying DNA sequence.",
        "The difference arises during RNA processing.",
        "Consider how intron removal and exon joining can vary.",
        45,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Cellular metabolism",
    section: "B/B",
    rows: [
      [
        "What is the net ATP yield from glycolysis of one free glucose molecule to two pyruvate molecules?",
        ["2 ATP", "4 ATP", "6 ATP", "32 ATP"],
        0,
        "Glycolysis consumes two ATP and produces four by substrate-level phosphorylation, for a net gain of two. It also produces two NADH; oxidative phosphorylation is not part of this ATP count.",
        "Distinguish gross production from net gain.",
        "Subtract the ATP investment from the four ATP produced.",
        60,
        "Quantitative reasoning",
      ],
      [
        "In human cells performing lactate fermentation, reducing pyruvate to lactate primarily allows glycolysis to continue by:",
        [
          "Producing oxygen",
          "Generating a proton gradient",
          "Regenerating NAD+",
          "Directly producing four additional ATP",
        ],
        2,
        "Lactate dehydrogenase oxidizes NADH to NAD+ as it reduces pyruvate. NAD+ is required by glyceraldehyde-3-phosphate dehydrogenase in glycolysis. The lactate reaction itself does not generate ATP.",
        "Track the electron carrier, not just the carbon product.",
        "Glycolysis needs an oxidized electron acceptor at the glyceraldehyde-3-phosphate step.",
        60,
        "Concept application",
      ],
      [
        "Where does the citric acid cycle occur in a typical human cell?",
        ["Cytosol", "Nucleus", "Lysosomal lumen", "Mitochondrial matrix"],
        3,
        "The cycle occurs primarily in the mitochondrial matrix. Succinate dehydrogenase is associated with the inner mitochondrial membrane, but the cycle is conventionally localized to the matrix.",
        "Distinguish glycolysis from mitochondrial oxidation.",
        "Consider the compartment containing most citric acid cycle enzymes.",
        45,
        "Concept application",
      ],
      [
        "An uncoupler increases proton permeability of the inner mitochondrial membrane. With adequate fuel and oxygen, which immediate pattern is expected?",
        [
          "ATP synthesis increases while oxygen use stops",
          "ATP synthesis falls while electron transport can continue",
          "The proton gradient becomes larger",
          "NADH can no longer donate electrons solely because the membrane leaks",
        ],
        1,
        "Proton leakage dissipates the gradient used by ATP synthase. Electron transport can continue, often with increased oxygen consumption, while ATP production becomes less efficient and more energy is released as heat.",
        "Separate electron flow from use of the proton gradient.",
        "Protons can return without driving ATP synthase.",
        75,
        "Experimental reasoning",
      ],
      [
        "During the electron transport chain, oxygen serves primarily as:",
        [
          "The terminal electron acceptor",
          "The carbon source for glucose",
          "A direct substrate of ATP synthase",
          "The electron donor to complex I",
        ],
        0,
        "Oxygen accepts electrons at complex IV and is reduced to water. NADH donates electrons to complex I; ATP synthase uses the proton gradient rather than oxygen directly.",
        "Trace electrons to the end of the chain.",
        "The final acceptor combines with electrons and protons to form water.",
        60,
        "Concept application",
      ],
      [
        "One round of beta oxidation of a saturated fatty acyl-CoA longer than four carbons shortens the chain by how many carbon atoms?",
        ["One", "Three", "Two", "Four"],
        2,
        "Each standard round releases a two-carbon acetyl-CoA and leaves a fatty acyl-CoA two carbons shorter. The final cleavage of a four-carbon chain yields two acetyl-CoA molecules.",
        "Identify the carbon-containing product released each round.",
        "An acetyl group contains two carbon atoms.",
        60,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Social psychology",
    section: "P/S",
    rows: [
      [
        "A student attributes a classmate's lateness to laziness without considering a transit delay. Which bias is best illustrated?",
        [
          "Self-serving bias",
          "Fundamental attribution error",
          "Hindsight bias",
          "Availability heuristic",
        ],
        1,
        "Fundamental attribution error overemphasizes dispositional explanations for another person's behavior while underweighting situational causes. The vignette contrasts a trait judgment with a plausible external constraint.",
        "Whose behavior is being explained, and how?",
        "Compare a personality explanation with a situational explanation.",
        60,
        "Concept application",
      ],
      [
        "A person publicly agrees with a group's clearly wrong answer to avoid rejection, despite privately knowing the correct answer. What best explains this?",
        [
          "Informational social influence",
          "Classical conditioning",
          "Social loafing",
          "Normative social influence",
        ],
        3,
        "Normative influence reflects a desire for acceptance or avoidance of rejection. Informational influence would involve treating others' judgments as evidence about what is correct.",
        "The person is seeking acceptance rather than information.",
        "Notice that private belief remains unchanged.",
        60,
        "Concept application",
      ],
      [
        "A skilled pianist performs a well-practiced piece better in front of an audience than alone. Which concept best fits?",
        [
          "Social facilitation",
          "Group polarization",
          "Deindividuation",
          "Bystander effect",
        ],
        0,
        "Social facilitation describes improved performance on well-learned or simple tasks in the presence of others. An audience can impair performance on unfamiliar or difficult tasks instead.",
        "The task is already well practiced.",
        "Consider how an audience affects dominant, well-learned responses.",
        60,
        "Concept application",
      ],
      [
        "Each person in a large crowd assumes someone else will call for help, reducing the likelihood that any one person acts. What mechanism is illustrated?",
        [
          "Operant extinction",
          "Cognitive dissonance",
          "Diffusion of responsibility",
          "Reciprocal determinism",
        ],
        2,
        "Diffusion of responsibility reduces an individual's perceived obligation when others are present. It is one mechanism contributing to the bystander effect.",
        "Responsibility is spread across multiple observers.",
        "Each person expects another person to intervene.",
        45,
        "Concept application",
      ],
      [
        "After joining a discussion, members of a mildly risk-seeking group endorse a more strongly risk-seeking position. This is an example of:",
        [
          "Social loafing",
          "Group polarization",
          "Role strain",
          "Stimulus discrimination",
        ],
        1,
        "Group polarization shifts a group's average position toward a more extreme version of its initial tendency. It differs from groupthink, which emphasizes pressures suppressing critical evaluation.",
        "Compare the direction of opinion before and after discussion.",
        "The group moves farther in its preexisting direction.",
        60,
        "Concept application",
      ],
      [
        "A person who values health but smokes minimizes evidence that smoking is harmful. Which concept best explains this rationalization?",
        [
          "Sensory adaptation",
          "Secure attachment",
          "Observational learning",
          "Cognitive dissonance reduction",
        ],
        3,
        "Conflict between a health-related belief and smoking behavior can create cognitive dissonance. Discounting evidence reduces the perceived inconsistency without changing the behavior.",
        "Identify the conflict between belief and behavior.",
        "Changing an interpretation can reduce discomfort from inconsistent cognitions.",
        60,
        "Concept application",
      ],
    ],
  },
  {
    topic: "Research methods",
    section: "P/S",
    rows: [
      [
        "Investigators randomly assign participants to an intervention or control group. What is the main purpose of random assignment?",
        [
          "Guarantee a representative population sample",
          "Ensure the hypothesis is correct",
          "Reduce systematic baseline differences between groups",
          "Eliminate every measurement error",
        ],
        2,
        "Random assignment balances measured and unmeasured confounders in expectation, improving causal inference. It does not guarantee perfect balance or population representativeness; random sampling addresses the latter.",
        "Distinguish assignment to groups from selection into a sample.",
        "Think about preexisting differences that could explain the outcome.",
        75,
        "Experimental reasoning",
      ],
      [
        "A study finds that coffee intake and stress scores are positively correlated. Which conclusion is justified by correlation alone?",
        [
          "Higher coffee intake is associated with higher stress scores",
          "Coffee necessarily causes stress",
          "Stress cannot influence coffee intake",
          "No third variable could explain the association",
        ],
        0,
        "A positive correlation establishes an association in the observed data. Direction of causation and confounding remain unresolved without additional design or evidence.",
        "Separate an association from a causal explanation.",
        "Reverse causation and common causes are still possible.",
        60,
        "Experimental reasoning",
      ],
      [
        "A depression questionnaire gives similar scores on repeated administrations when participants' underlying states are stable. Which property is most directly demonstrated?",
        [
          "External validity",
          "Random assignment",
          "Criterion validity",
          "Test–retest reliability",
        ],
        3,
        "Test–retest reliability concerns measurement consistency over time when the construct is stable. Consistency alone does not establish that the instrument measures depression accurately.",
        "The evidence concerns consistency across time.",
        "Distinguish reliability from whether the intended construct is actually measured.",
        60,
        "Experimental reasoning",
      ],
      [
        "A researcher rejects a null hypothesis that is actually true. What has occurred?",
        [
          "A type II error",
          "A type I error",
          "Perfect statistical power",
          "A true negative",
        ],
        1,
        "A type I error is a false positive: rejecting a true null hypothesis. A type II error is failing to reject a false null hypothesis.",
        "The claimed effect is a false positive.",
        "Map false positive to type I and false negative to type II.",
        45,
        "Concept application",
      ],
      [
        "In a screening study, 80 of 100 people who truly have a condition test positive. What is the test's sensitivity?",
        [
          "80%",
          "20%",
          "Cannot be found without the false-positive count",
          "125%",
        ],
        0,
        "Sensitivity is true positives divided by all people with the condition: 80/100 = 80%. False positives are needed for other measures, such as positive predictive value, but not for this calculation.",
        "Condition on having the condition.",
        "Divide true positives by true positives plus false negatives.",
        75,
        "Quantitative reasoning",
      ],
      [
        "A study operationalizes stress as a participant's score on a specified questionnaire. What does this operational definition accomplish?",
        [
          "Proves that stress has only one cause",
          "Guarantees a causal conclusion",
          "Specifies how an abstract construct is measured",
          "Ensures that all participants have identical stress",
        ],
        2,
        "An operational definition translates a construct into a concrete measurement or procedure. It supports reproducibility but does not by itself establish validity, causality, or equal scores.",
        "Ask how another researcher would reproduce the measurement.",
        "The definition connects an abstract idea to an observable procedure.",
        60,
        "Experimental reasoning",
      ],
    ],
  },
];

export const expandedQuestions: FullQuestion[] = groups.flatMap(
  (group, groupIndex) =>
    group.rows.map((r, index) => ({
      id: `expansion-01-${String(groupIndex + 1).padStart(2, "0")}-${String(index + 1).padStart(2, "0")}`,
      topic: group.topic,
      section: group.section,
      prompt: r[0],
      options: r[1],
      answer: r[2],
      explanation: r[3],
      hints: [r[4], r[5]],
      target_seconds: r[6],
      skill: r[7],
      difficulty: "Foundational",
      version: 1,
      source:
        "Original AI-authored practice · not official or calibrated MCAT material",
      passage: null,
    })),
);
