import { FullQuestion } from "./types";
import { expandedQuestions } from "./expanded-questions";
import { reviewedQuestions } from "./reviewed-questions";

// Original, AI-authored foundational practice. These are not official or calibrated MCAT items.
const rows: [
  string,
  string,
  string,
  string[],
  number,
  string,
  string,
  string,
  number,
][] = [
  [
    "Dilution",
    "C/P",
    "A 20 mL sample of 0.30 M glucose is diluted to a total volume of 60 mL. What is the final concentration?",
    ["0.05 M", "0.10 M", "0.30 M", "0.90 M"],
    1,
    "Dilution conserves solute: C₂ = C₁V₁/V₂ = 0.30 × 20/60 = 0.10 M. The volume triples, so concentration falls to one third.",
    "Use conservation of moles.",
    "Write C₁V₁ = C₂V₂. Use the final total volume.",
    60,
  ],
  [
    "Dilution",
    "C/P",
    "How many moles of NaCl are present in 250 mL of a 0.20 M solution?",
    ["0.80 mol", "0.050 mol", "50 mol", "0.008 mol"],
    1,
    "Convert 250 mL to 0.250 L, then n = CV = 0.20 × 0.250 = 0.050 mol.",
    "Molarity is moles per liter.",
    "Convert the volume to liters before multiplying.",
    60,
  ],
  [
    "Dilution",
    "C/P",
    "Equal volumes of 0.10 M and 0.30 M glucose are mixed. Assuming additive volumes, what is the resulting concentration?",
    ["0.10 M", "0.15 M", "0.20 M", "0.40 M"],
    2,
    "For equal volumes, the total moles divided by total volume gives the average concentration: (0.10 + 0.30)/2 = 0.20 M.",
    "Add moles, not concentrations.",
    "Choose 1 L of each solution to simplify the calculation.",
    60,
  ],
  [
    "Dilution",
    "C/P",
    "A 0.020 M solution of AlCl₃ dissociates completely. What is the chloride-ion concentration?",
    ["0.0067 M", "0.020 M", "0.040 M", "0.060 M"],
    3,
    "Each formula unit yields three chloride ions. [Cl⁻] = 3 × 0.020 = 0.060 M.",
    "Read the chloride subscript.",
    "One mole of AlCl₃ yields three moles of chloride ions.",
    45,
  ],
  [
    "Stoichiometry",
    "C/P",
    "For 2 H₂ + O₂ → 2 H₂O, 0.30 mol H₂ reacts with excess oxygen. How much water forms?",
    ["0.15 mol", "0.30 mol", "0.60 mol", "0.90 mol"],
    1,
    "The coefficient ratio H₂:H₂O is 2:2, or 1:1. Therefore 0.30 mol H₂ produces 0.30 mol H₂O.",
    "Use the reactant-to-product coefficient ratio.",
    "The coefficients of hydrogen and water are equal.",
    60,
  ],
  [
    "Stoichiometry",
    "C/P",
    "For N₂ + 3 H₂ → 2 NH₃, a mixture contains 0.20 mol N₂ and 0.30 mol H₂. What is the maximum NH₃ yield?",
    ["0.10 mol", "0.20 mol", "0.30 mol", "0.40 mol"],
    1,
    "Hydrogen is limiting: 0.30/3 = 0.10 mol reaction units, producing 0.10 × 2 = 0.20 mol NH₃.",
    "Identify the limiting reactant first.",
    "Divide each reactant amount by its coefficient and compare.",
    90,
  ],
  [
    "Stoichiometry",
    "C/P",
    "CaCO₃ → CaO + CO₂. If 5.0 g CaCO₃ decomposes completely, how many grams of CO₂ form? Use 100 g/mol for CaCO₃ and 44 g/mol for CO₂.",
    ["1.1 g", "2.2 g", "4.4 g", "5.0 g"],
    1,
    "5.0/100 = 0.050 mol CaCO₃. The 1:1 ratio yields 0.050 mol CO₂; multiplying by 44 g/mol gives 2.2 g.",
    "Convert mass to moles first.",
    "Use the 1:1 mole ratio, then convert product moles to grams.",
    90,
  ],
  [
    "Stoichiometry",
    "C/P",
    "For 4 Al + 3 O₂ → 2 Al₂O₃, 0.20 mol Al reacts completely with 0.25 mol O₂ initially present. How much O₂ remains?",
    ["0.05 mol", "0.10 mol", "0.15 mol", "0.20 mol"],
    1,
    "O₂ consumed = 0.20 × 3/4 = 0.15 mol. Remaining O₂ = 0.25 − 0.15 = 0.10 mol.",
    "Calculate oxygen consumed before subtracting.",
    "Multiply aluminum moles by 3/4, then subtract from the initial oxygen.",
    90,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "A reversible competitive inhibitor has which effect on Michaelis–Menten parameters?",
    [
      "Decreases Vmax only",
      "Increases apparent Km; Vmax unchanged",
      "Decreases Km and Vmax",
      "Increases Vmax only",
    ],
    1,
    "A competitive inhibitor competes for the active site. More substrate is needed for half-maximal velocity, increasing apparent Km; sufficient substrate restores the same Vmax.",
    "Consider whether excess substrate can overcome inhibition.",
    "Competitive inhibition changes substrate concentration needed, not maximum catalytic capacity.",
    60,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "For an enzyme following Michaelis–Menten kinetics, what is v when [S] = Km?",
    ["Vmax", "Vmax/4", "Vmax/2", "2Vmax"],
    2,
    "v = Vmax[S]/(Km + [S]). When [S] = Km, the numerator is VmaxKm and the denominator is 2Km, giving Vmax/2.",
    "Substitute into the Michaelis–Menten equation.",
    "The denominator becomes twice Km.",
    60,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "An ideal pure noncompetitive inhibitor changes which parameters?",
    [
      "Vmax decreases; Km unchanged",
      "Vmax unchanged; Km increases",
      "Both increase",
      "Both remain unchanged",
    ],
    0,
    "In pure noncompetitive inhibition, inhibitor affinity for free enzyme and enzyme–substrate complex is equal. Vmax falls while Km stays the same. Mixed inhibition need not preserve Km.",
    "Distinguish pure noncompetitive inhibition from mixed inhibition.",
    "Effective catalytic capacity decreases without changing substrate affinity in the ideal case.",
    60,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "On a Lineweaver–Burk plot of 1/v against 1/[S], the y-intercept equals:",
    ["Km", "−1/Km", "Vmax", "1/Vmax"],
    3,
    "Taking the reciprocal gives 1/v = (Km/Vmax)(1/[S]) + 1/Vmax. The constant term is the y-intercept.",
    "Compare the reciprocal equation with y = mx + b.",
    "The term that does not multiply 1/[S] is the intercept.",
    60,
  ],
  [
    "Membrane transport",
    "B/B",
    "A substance moves down its concentration gradient through a carrier protein without ATP use. This is:",
    [
      "Primary active transport",
      "Facilitated diffusion",
      "Endocytosis",
      "Secondary active transport",
    ],
    1,
    "Facilitated diffusion uses a membrane protein to move a substance down its gradient without direct energy input. Active transport couples movement to an energy source.",
    "Consider both direction and energy use.",
    "A carrier protein does not automatically make transport active.",
    45,
  ],
  [
    "Membrane transport",
    "B/B",
    "The sodium–potassium ATPase typically transports, per ATP hydrolyzed:",
    [
      "3 Na⁺ out and 2 K⁺ in",
      "2 Na⁺ out and 3 K⁺ in",
      "3 Na⁺ in and 2 K⁺ out",
      "2 Na⁺ in and 2 K⁺ out",
    ],
    0,
    "The pump exports three sodium ions and imports two potassium ions per ATP, creating a net outward positive charge.",
    "The pump is electrogenic.",
    "More positive ions leave than enter in each cycle.",
    45,
  ],
  [
    "Membrane transport",
    "B/B",
    "A cell is placed in a solution with a higher concentration of nonpenetrating solutes than its cytoplasm. What initially happens?",
    [
      "Water enters and the cell swells",
      "Water leaves and the cell shrinks",
      "No net water movement",
      "Solutes must all leave the cell",
    ],
    1,
    "The external solution is hypertonic. Water moves outward toward the higher effective solute concentration, shrinking the cell.",
    "Only nonpenetrating solutes determine this tonicity comparison.",
    "Water moves toward the compartment with more nonpenetrating solute.",
    60,
  ],
  [
    "Membrane transport",
    "B/B",
    "Which molecule most readily crosses a pure phospholipid bilayer by simple diffusion?",
    ["Na⁺", "Glucose", "O₂", "A large charged peptide"],
    2,
    "Small nonpolar molecules such as oxygen cross the hydrophobic bilayer readily. Ions and large polar molecules face much larger barriers.",
    "Think about the hydrophobic interior of the membrane.",
    "Small size and lack of charge favor simple diffusion.",
    45,
  ],
  [
    "Circuits",
    "C/P",
    "A 12 V potential difference is applied across a 4 Ω resistor. What current flows?",
    ["0.33 A", "3 A", "8 A", "48 A"],
    1,
    "Ohm’s law gives I = V/R = 12/4 = 3 A.",
    "Use Ohm’s law.",
    "Solve V = IR for current.",
    60,
  ],
  [
    "Circuits",
    "C/P",
    "Two resistors of 3 Ω and 6 Ω are connected in parallel. What is their equivalent resistance?",
    ["2 Ω", "3 Ω", "9 Ω", "18 Ω"],
    0,
    "1/R = 1/3 + 1/6 = 1/2, so R = 2 Ω. Parallel resistance is lower than the smallest branch resistance.",
    "Add reciprocals for parallel resistors.",
    "Use a common denominator of six.",
    75,
  ],
  [
    "Circuits",
    "C/P",
    "A resistor carries 2 A with a 6 V potential difference. How much power does it dissipate?",
    ["3 W", "8 W", "12 W", "24 W"],
    2,
    "Electrical power P = IV = 2 × 6 = 12 W.",
    "Power is energy transferred per unit time.",
    "Use P = IV.",
    45,
  ],
  [
    "Circuits",
    "C/P",
    "Two ideal resistors in series have which quantity necessarily equal through each?",
    ["Voltage drop", "Resistance", "Power dissipation", "Current"],
    3,
    "A series path has no branch points, so charge conservation requires the same current through both resistors. Voltage drops depend on resistance.",
    "Consider conservation of charge along a single path.",
    "Charge cannot accumulate indefinitely between the resistors.",
    45,
  ],
  [
    "Learning & memory",
    "P/S",
    "A student studies more often after an unpleasant reminder stops whenever they study. This illustrates:",
    [
      "Positive punishment",
      "Negative reinforcement",
      "Negative punishment",
      "Extinction",
    ],
    1,
    "Removing an aversive stimulus increases studying, so this is negative reinforcement. Negative means removal; reinforcement means the behavior increases.",
    "Separate adding/removing a stimulus from increasing/decreasing behavior.",
    "An unpleasant stimulus is removed and the behavior increases.",
    60,
  ],
  [
    "Learning & memory",
    "P/S",
    "An old password interferes with remembering a new password. This is:",
    [
      "Retroactive interference",
      "Proactive interference",
      "Classical conditioning",
      "State-dependent memory",
    ],
    1,
    "Proactive interference occurs when earlier learning disrupts recall of newer material. Retroactive interference is the reverse direction.",
    "Identify which memory interferes with which.",
    "The old memory acts forward on the new memory.",
    45,
  ],
  [
    "Learning & memory",
    "P/S",
    "A previously conditioned response weakens when the conditioned stimulus is repeatedly presented without the unconditioned stimulus. This is:",
    ["Generalization", "Acquisition", "Extinction", "Discrimination"],
    2,
    "Repeated unreinforced presentations of the conditioned stimulus reduce the conditioned response: extinction. This does not necessarily erase the original association.",
    "The association is no longer reinforced.",
    "The response becomes weaker over repeated trials.",
    45,
  ],
  [
    "Learning & memory",
    "P/S",
    "Remembering how to ride a bicycle primarily involves:",
    [
      "Episodic memory",
      "Semantic memory",
      "Procedural memory",
      "Sensory memory",
    ],
    2,
    "Procedural memory supports learned skills and actions. Episodic memory concerns events; semantic memory concerns facts and concepts.",
    "Distinguish knowing how from knowing that.",
    "Motor skills are a form of implicit memory.",
    45,
  ],
];
rows.push(
  [
    "Dilution",
    "C/P",
    "What volume of 2.0 M stock is required to prepare 100 mL of 0.10 M solution?",
    ["5 mL", "10 mL", "20 mL", "50 mL"],
    0,
    "C₁V₁ = C₂V₂, so V₁ = 0.10 × 100 / 2.0 = 5 mL. Dilute that stock to a final total of 100 mL.",
    "Conserve solute moles.",
    "Rearrange the dilution equation to solve for the stock volume.",
    60,
  ],
  [
    "Dilution",
    "C/P",
    "100 mL of 0.50 M glucose loses water by evaporation until 50 mL remains. No glucose is lost. What is the new concentration?",
    ["0.25 M", "0.50 M", "1.0 M", "2.0 M"],
    2,
    "Halving the volume while retaining all solute doubles its concentration, from 0.50 M to 1.0 M.",
    "The number of solute moles stays constant.",
    "Divide the original volume by the remaining volume.",
    60,
  ],
  [
    "Stoichiometry",
    "C/P",
    "2 KClO₃ → 2 KCl + 3 O₂. How much O₂ forms when 0.40 mol KClO₃ decomposes completely?",
    ["0.20 mol", "0.40 mol", "0.60 mol", "1.20 mol"],
    2,
    "The O₂:KClO₃ coefficient ratio is 3:2. Thus 0.40 × 3/2 = 0.60 mol O₂ forms.",
    "Read the balanced coefficients.",
    "Multiply the reactant amount by the product-to-reactant ratio.",
    60,
  ],
  [
    "Stoichiometry",
    "C/P",
    "A reaction has a theoretical product yield of 8.0 g and an actual yield of 6.0 g. What is the percent yield?",
    ["25%", "60%", "75%", "133%"],
    2,
    "Percent yield = actual/theoretical × 100 = 6.0/8.0 × 100 = 75%.",
    "Compare the obtained mass with the maximum predicted mass.",
    "Actual yield is the numerator.",
    60,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "At saturating substrate concentration, doubling the amount of active enzyme does what to Vmax?",
    ["Halves it", "Leaves it unchanged", "Doubles it", "Quadruples it"],
    2,
    "Vmax = kcat × total active enzyme concentration. Doubling active enzyme doubles Vmax if other conditions remain constant.",
    "Vmax depends on the number of catalytic sites.",
    "The proportionality to enzyme concentration is linear.",
    60,
  ],
  [
    "Enzyme kinetics",
    "B/B",
    "An enzyme has Vmax = 90 μmol/min and Km = 2 mM. At [S] = 4 mM, what is its initial rate under Michaelis–Menten kinetics?",
    ["30 μmol/min", "45 μmol/min", "60 μmol/min", "90 μmol/min"],
    2,
    "v = Vmax[S]/(Km + [S]) = 90 × 4/(2 + 4) = 60 μmol/min.",
    "Use the Michaelis–Menten equation.",
    "The substrate fraction is 4/(2 + 4).",
    90,
  ],
  [
    "Membrane transport",
    "B/B",
    "A sodium–glucose symporter uses the sodium gradient to move glucose against its gradient. This is:",
    [
      "Simple diffusion",
      "Facilitated diffusion",
      "Primary active transport",
      "Secondary active transport",
    ],
    3,
    "Secondary active transport couples favorable movement of one species down its electrochemical gradient to unfavorable movement of another. The transporter does not directly hydrolyze ATP.",
    "Identify the immediate energy source for this transporter.",
    "An existing ion gradient provides the energy.",
    60,
  ],
  [
    "Membrane transport",
    "B/B",
    "In a pure lipid bilayer, increasing the proportion of unsaturated fatty-acid tails generally has what effect at a fixed moderate temperature?",
    [
      "Increases fluidity",
      "Decreases fluidity",
      "Eliminates the hydrophobic core",
      "Makes all ions freely permeable",
    ],
    0,
    "Cis double bonds introduce kinks that reduce close packing of lipid tails, generally increasing membrane fluidity.",
    "Consider how tightly the tails can pack.",
    "Kinked tails have fewer close contacts with neighboring tails.",
    60,
  ],
  [
    "Circuits",
    "C/P",
    "A 2 Ω and a 4 Ω resistor are connected in series to an ideal 12 V source. What is the voltage across the 4 Ω resistor?",
    ["2 V", "4 V", "6 V", "8 V"],
    3,
    "Total resistance is 6 Ω, so current is 12/6 = 2 A. The drop across 4 Ω is IR = 2 × 4 = 8 V.",
    "Find total resistance, then the series current.",
    "Use the common current to calculate the drop across 4 Ω.",
    90,
  ],
  [
    "Circuits",
    "C/P",
    "A 2 μF capacitor is connected across a 3 V source. How much charge does it store?",
    ["0.67 μC", "1.5 μC", "5 μC", "6 μC"],
    3,
    "Q = CV = 2 μF × 3 V = 6 μC.",
    "Capacitance relates stored charge to voltage.",
    "Use Q = CV and retain the micro prefix.",
    60,
  ],
  [
    "Learning & memory",
    "P/S",
    "Remembering what you ate at your own birthday dinner last year primarily involves:",
    [
      "Procedural memory",
      "Episodic memory",
      "Classical conditioning",
      "Sensory memory",
    ],
    1,
    "Episodic memory concerns personally experienced events in their temporal and contextual setting.",
    "This is a personally experienced event.",
    "Distinguish autobiographical events from general facts.",
    45,
  ],
  [
    "Learning & memory",
    "P/S",
    "A learned response occurs to a new stimulus similar to the original conditioned stimulus. This is:",
    [
      "Stimulus discrimination",
      "Spontaneous recovery",
      "Stimulus generalization",
      "Negative reinforcement",
    ],
    2,
    "Stimulus generalization occurs when stimuli resembling the conditioned stimulus also evoke the learned response.",
    "Focus on the similarity between the two stimuli.",
    "The response extends beyond the exact original stimulus.",
    45,
  ],
);
export const questions: FullQuestion[] = [
  ...rows.map((r, i) => ({
    id: `sample-${String(i + 1).padStart(2, "0")}`,
    topic: r[0],
    section: r[1],
    skill: r[8] >= 75 ? "Quantitative reasoning" : "Concept application",
    difficulty: "Foundational",
    prompt: r[2],
    options: r[3],
    answer: r[4],
    explanation: r[5],
    hints: [r[6], r[7]],
    target_seconds: r[8],
    version: 1,
    source:
      "Original AI-authored starter question · not official MCAT material",
    passage: null,
  })),
  ...expandedQuestions,
  ...reviewedQuestions,
];
