export type Mode = "training" | "rapid";
export type Question = {
  id: string;
  topic: string;
  section: string;
  skill: string;
  difficulty: string;
  prompt: string;
  options: string[];
  target_seconds: number;
  version: number;
  source: string;
  passage?: string | null;
  passage_id?: string;
  passage_title?: string;
  passage_order?: number;
  figures?: { id: string; src: string; caption: string; alt: string; width: number; height: number }[];
};
export type FullQuestion = Question & {
  answer: number;
  explanation: string;
  hints: string[];
};
export type Attempt = {
  family_id?: string;
  passage_id?: string | null;
  annotation?: import('./canonical-topics').Annotation | null;
  exposure_known?: boolean;
  prior_hint?: boolean;
  prior_answer?: boolean;
  prior_solution?: boolean;
  prior_item?: boolean;
  prior_passage?: boolean;
  difficulty?: string;
  difficulty_status?: string;
  id?: string;
  session_id: string;
  question_id: string;
  topic: string;
  section: string;
  skill: string;
  mode: Mode;
  correct: boolean;
  active_ms: number;
  target_seconds: number;
  hints_used: number;
  repeated: boolean;
  timing_valid: boolean;
  created_at: string;
  selected: number;
  points: number;
  question_version: number;
};
export type StudySession = {
  id: string;
  mode: Mode;
  question_ids: string[];
  created_at: string;
  completed_at: string | null;
  cursor: number;
  score: number;
};
export type Feedback = {
  correct: boolean;
  answer: number;
  explanation: string;
  points: number;
};
export type PracticeUnit = {
  session: StudySession;
  question: Question | null;
  questions: Question[];
  hints: Record<string, string[]>;
};
export type UnitFeedback = Record<string, Feedback>;
export type Report = {
  session_summary: string;
  overall_summary: string;
  strengths: string[];
  weaknesses: string[];
  next_steps: string[];
  overall_strengths: string[];
  overall_weaknesses: string[];
  overall_next_steps: string[];
  caveat: string;
};
